"""Add MPESA fields to Booking model

Revision ID: 6a212cbfa96b
Revises: f7bfc2104dfd
Create Date: 2026-02-10 13:30:59.823329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a212cbfa96b'
down_revision = 'f7bfc2104dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mover_id', sa.Integer(), nullable=True),
    sa.Column('pickup_address_id', sa.Integer(), nullable=False),
    sa.Column('dropoff_address_id', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('volume_cubic_meters', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='quotestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dropoff_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['mover_id'], ['movers.id'], ),
    sa.ForeignKeyConstraint(['pickup_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookings', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('mpesa_receipt_number', sa.String(length=20), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatus'), nullable=False))
    op.add_column('bookings', sa.Column('checkout_request_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'checkout_request_id')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'mpesa_receipt_number')
    op.drop_column('bookings', 'amount')
    op.drop_table('quotes')
    # ### end Alembic commands ###
