"""Add location tracking fields to Mover model

Revision ID: e06fc3c8ef74
Revises: 56cd3fa6b73a
Create Date: 2026-02-12 14:53:42.591029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06fc3c8ef74'
down_revision = '6a212cbfa96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_location_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movers', schema=None) as batch_op:
        batch_op.drop_column('last_location_update')
        batch_op.drop_column('last_lng')
        batch_op.drop_column('last_lat')

    # ### end Alembic commands ###
