from flask import Blueprint, request
from app.utils.response import success, error
from app.utils.decorators import jwt_required
from app.utils.validators import validate_request

inventory_bp = Blueprint('inventory', __name__, url_prefix='/inventory')

@inventory_bp.route('', methods=['GET'])
@jwt_required
def get_user_inventory(current_user):
    """
    Retrieves the inventory for the current user.
    """
    # In a real application, you would fetch the user's inventory from the database.
    # This is a placeholder response.
    user_inventory = [
        {"item_id": 1, "name": "Sofa", "quantity": 1},
        {"item_id": 2, "name": "Box of Books", "quantity": 5},
        {"item_id": 3, "name": "Lamp", "quantity": 2}
    ]
    return success(user_inventory)

@inventory_bp.route('', methods=['POST'])
@jwt_required
@validate_request('name', 'quantity')
def add_inventory_item(current_user):
    """
    Adds an item to the user's inventory.
    """
    data = request.get_json()
    
    # Placeholder for adding an item
    new_item = {
        "item_id": 4, # Typically generated by the database
        "name": data['name'],
        "quantity": data['quantity']
    }

    return success(new_item, 201)
